SELECT * FROM SPENDING, TYPE_SPENDING, TYPE WHERE idSpending = spending AND type = idType AND idSpending = 1;



SELECT * FROM SPENDING INNER JOIN TYPE_SPENDING ON SPENDING.idSpending = TYPE_SPENDING.spending INNER JOIN TYPE ON TYPE_SPENDING.type = TYPE.idType WHERE idSpending = 1 ORDER BY name;


SELECT * FROM SPENDING INNER JOIN TYPE_SPENDING ON SPENDING.idSpending = TYPE_SPENDING.spending INNER JOIN TYPE ON TYPE_SPENDING.type = TYPE.idType WHERE SPENDING.owner = adri229 ORDER BY name;



SELECT * FROM SPENDING LEFT OUTER JOIN TYPE_SPENDING ON SPENDING.idSpending = TYPE_SPENDING.spending LEFT OUTER JOIN TYPE ON TYPE_SPENDING.type = TYPE.idType WHERE SPENDING.owner = 'adri229' ORDER BY name;

SELECT * FROM SPENDING LEFT JOIN TYPE_SPENDING ON SPENDING.idSpending = TYPE_SPENDING.spending LEFT JOIN TYPE ON TYPE_SPENDING.type = TYPE.idType WHERE SPENDING.owner = 'adri229' ORDER BY name;


select * from STOCK WHERE dateStock < '2016-02-25' ORDER BY dateStock DESC LIMIT 1;


INSERT INTO `STOCK` (`dateStock`,`total`,`owner`) VALUES (DATE_FORMAT('2016-05-24T22:00:00.000Z',GET_FORMAT(DATE,'EUR')),'1200','adri229');


SELECT DATE_FORMAT('2016-05-24T22:00:00.000Z',GET_FORMAT(DATE,'EUR'));